### ISSUE TITLE
Software crashes on ESP32 due to single line error

### ISSUE THREAD

**Issue by tgrech1997** [Lightwell-bg/ssdpAWS#1]
Software crashes on ESP32 due to line 25 of ssdpAWS.cpp, can be fixed simply by wrapping IP address in a String constructor:
            SSDP.setModelURL("http://"+String(WiFi.status() != WL_CONNECTED ? WiFi.softAPIP() : WiFi.localIP()));

**Comment by Lightwell-bg** [comment]
Thank you!
